<a href="https://colab.research.google.com/github/QueenRae7/QueenRae7/blob/main/Copy_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2 Dimensional Numpy Array

In [ ]:
import numpy as np

In [ ]:
# Create a 2 Dimensional numpy array of of shape(3, 4)
Arr1 = np.array([[10, 20, 30, 49], [30, 87, 34, 23], [78, 23, 12, 89]])
print(Arr1)

[[10 20 30 49]
 [30 87 34 23]
 [78 23 12 89]]


In [ ]:
# shape
print(Arr1.shape)

(3, 4)


In [ ]:
# dimension
print(Arr1.ndim)

2


In [ ]:
# dtype -- The type of element it contains
print(Arr1.dtype)

int64


## Create a numpy array of shape (4, 2)

In [ ]:
Arr2 = np.array([[10, 20], [30, 50], [40, 34], [20, 89]])
print(Arr2)

[[10 20]
 [30 50]
 [40 34]
 [20 89]]


In [ ]:
print(Arr2.shape)
print(Arr2.ndim)
print(Arr2.dtype)
print(Arr2.size) # number of element

(4, 2)
2
int64
8


Task - Create a numpy array of shape (5, 4)

In [ ]:
Arr3 = np.array([['a','b','c','d'], ['e','f','g','h'], ['i','j','k','l'], ['m','n','o','p'],
                 ['r','s','t','u']])
print(Arr3)

[['a' 'b' 'c' 'd']
 ['e' 'f' 'g' 'h']
 ['i' 'j' 'k' 'l']
 ['m' 'n' 'o' 'p']
 ['r' 's' 't' 'u']]


In [ ]:
print(Arr3.shape)

(5, 4)


# 3 Dimensional Array

In [ ]:
Arr4 = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(Arr4)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [ ]:
print(Arr4.shape)

(1, 4, 2)


In [ ]:
Arr5 = np.array([[[1,2],[3,4],[5,6],[7,8]],[[3,2],[9,4],[3,6],[7,8]]])
print(Arr5)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]

 [[3 2]
  [9 4]
  [3 6]
  [7 8]]]


In [ ]:
print(Arr5.shape)

(2, 4, 2)


### np.zeros() --- it will generate the matrix of 0

In [ ]:
Arr6 = np.zeros([4,5])
print(Arr6)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
Arr6 = np.zeros([4,5], dtype = 'int')
print(Arr6)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### np.ones() --- it wil generate the matrix containing the all 1

In [ ]:
Arr7 = np.ones([4, 3])
print(Arr7)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# converting into the integer

Arr7 = np.ones([4, 3], dtype = 'int')
print(Arr7)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


## arange() -- it will generate one dimentional array from the defined range

In [ ]:
# generate one numpy array from 0 to 10

Arr8 = np.arange(0, 11)
print(Arr8)
print(type(Arr8))

[ 0  1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [ ]:
Arr9 = np.arange(3, 21).reshape(6, 3)
print(Arr9)
print(Arr9.size)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]
18


In [ ]:
print(Arr9.ndim)

2


In [ ]:
# converting 2D data into 1D

In [ ]:
Arr9

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [ ]:
Arr10 = Arr9.reshape(18)
Arr10

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [ ]:
# second approach

Arr11 = Arr9.flatten()
Arr11

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [ ]:
Arr12 = Arr11.reshape(2, 3, 3)
print(Arr12)
print(Arr12.ndim)

[[[ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]]]
3
